### ISSUE TITLE
Entities invisible/Error

### ISSUE THREAD

**Issue by ghost** [VisiVersa/Manic#1] opened 2023-01-17 07:17 UTC
https://mclo.gs/pJeJk5X
Mobs from manic appear as invisible aside from the error texture replacing the head region

**Comment by Nycleo** [comment] 2023-09-17 13:50
Still an issue on the 1.20.1 version.
Is there any way to fix this? :')
Idk if its because of the same problem than here...

**Comment by ward-hop** [comment] 2023-10-07 16:06
Same issue here, on 1.20.1.
Also applies to mobs from Sanguine.
Entities are invisible, with models apparently replaced by other textures, in my case potions.

**Comment by ShokCat** [comment] 2023-12-18 01:46
I've found out that this issue is caused by sodium for some reason, not sure if that'll help or not.

**Comment by tiigerbones** [comment] 2024-01-03 15:37
Def need a fix still on 1.20.1
both mods have this issue going below sodium 5.0 would really suck

**Comment by VisiVersa** [comment] 2024-02-13 12:19
Please read the FAQ, sorry for a year's late response but I hope you figured it out by now
Also the sodium issue is fixed in next (unreleased) version according to beta tests

**Closed by VisiVersa** 2024-02-13 12:19 UTC
